In [141]:
import random
import numpy as np
import pandas as pd

random.seed(7890)




n_class  p_class  n_obs
0        3     1.00   1000
1        2     0.70   1000
2        2     0.55   1000
3        2     0.30   1000


Y  X1  X2  X3
0    1   0   0   2
1    0   1   1   1
2    2   1   2   1
3    1   1   1   2
4    1   2   1   0
..  ..  ..  ..  ..
995  2   2   1   1
996  0   2   0   0
997  0   1   1   0
998  0   1   1   0
999  0   2   0   1

[1000 rows x 4 columns]

In [187]:
## synthetic dataset generator, with 3 parameters:
### number of classes of each variale (not appliable to Y)
### probablity of each class in each variable
### total number of observations 

def df_gen(n_class, p_class, n_obs):
    meta = pd.DataFrame(
        {"n_class" : n_class,
        'p_class': p_class,
        "n_obs" : np.repeat(n_obs, len(n_class))
        }
        )

    df = pd.DataFrame({})
    print(meta)
    # print(meta.loc[j, 'n_class'], meta.loc[j, 'p_class'], meta.loc[j, 'n_obs'])

    for j in range(0, meta.shape[0]) :
        randomlist = []
        if j == 0 :
            var = ['Y']
            for i in range(0, meta.loc[j,'n_obs']):
                n = np.random.randint(0,meta.loc[j,'n_class'])
                randomlist.append(n)
        else: 
            var = ['X' + str(j)]
            randomlist = np.random.binomial(n = meta.loc[j, 'n_class'], p = meta.loc[j, 'p_class'], size = meta.loc[j, 'n_obs'])
            
        df = pd.concat([df, pd.DataFrame(randomlist, columns = var )], axis = 1)
    return(df)

df1 = df_gen([3, 2, ], [1, .7, ], 1000)


df1

n_class  p_class  n_obs
0        3      1.0   1000
1        2      0.7   1000


Y  X1
0    1   2
1    0   1
2    0   0
3    1   2
4    1   1
..  ..  ..
995  0   2
996  0   1
997  0   2
998  0   1
999  0   1

[1000 rows x 2 columns]

In [193]:
##  Economics Gain Matric generator
### To simplify the result, the econ. gain will be set as 1 for the correct assignment and 0 for non-correct assignments


def egmatrix_gen(df) :
 dim = len(df['Y'].value_counts())
 eg_matrix = np.diag(np.repeat(1,dim))
 return (eg_matrix)

print(egmatrix_gen(df1))



[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [204]:
# print(df1[df1.Y == 0])

# temp = pd.DataFrame(df1['Y'].value_counts().index,  df1['Y'].value_counts() / len(df1), columns = ['K', 'Pc'])

print(temp)



0
Y       
0.359  1
0.326  2
0.315  0


In [175]:

def dis_bayes (train, test): 




    meas_space, 
    K, 
    e, 
    p_d_c, 
    p_c

    p_c_d = (p_d_c * p_c) / p_d











dis_bayes(df1)





AttributeError: 'Series' object has no attribute 'value_count'

In [ ]:

def 










